# Generated by Django 4.2.6 on 2024-02-28 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_employee_comment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_recurring_bills',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.fin_company_details'),
        ),
    ]
