# Generated by Django 4.2.6 on 2024-02-01 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_fin_vendors_recurring_bill_items_recurring_bills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurring_bill_reference',
            name='action',
        ),
        migrations.RemoveField(
            model_name='recurring_bill_reference',
            name='date',
        ),
        migrations.RemoveField(
            model_name='recurring_bill_reference',
            name='recurring_bill',
        ),
        migrations.AddField(
            model_name='recurring_bill_reference',
            name='reference_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Recurring_Bill_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.fin_company_details')),
                ('login_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.fin_login_details')),
                ('recurring_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.recurring_bills')),
            ],
        ),
    ]
