# Generated by Django 4.2.6 on 2024-03-23 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_fin_recurring_bills_customer_billing_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fin_recurring_bill_items',
            old_name='tax_rate',
            new_name='tax_rate_gst',
        ),
        migrations.AddField(
            model_name='fin_recurring_bill_items',
            name='tax_rate_igst',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 23)),
        ),
        migrations.AlterField(
            model_name='fin_attendance_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 23)),
        ),
        migrations.AlterField(
            model_name='fin_attendance_history',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 23)),
        ),
        migrations.AlterField(
            model_name='holiday_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 23)),
        ),
    ]
