# Generated by Django 4.2.6 on 2024-02-08 05:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_employee_comment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fin_Recurring_Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurring_bill_number', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_number', models.IntegerField(blank=True, null=True)),
                ('bill_number', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('expected_shipment_date', models.DateField(blank=True, null=True)),
                ('purchase_order_number', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=255, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=255, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='document')),
                ('sub_total', models.IntegerField(blank=True, null=True)),
                ('cgst', models.IntegerField(blank=True, null=True)),
                ('sgst', models.IntegerField(blank=True, null=True)),
                ('taxAmount_igst', models.IntegerField(blank=True, null=True)),
                ('shipping_charge', models.IntegerField(blank=True, null=True)),
                ('adjustment', models.IntegerField(blank=True, null=True)),
                ('grand_total', models.IntegerField(blank=True, null=True)),
                ('advanceAmount_paid', models.IntegerField(blank=True, null=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('company_payment_terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.fin_company_payment_terms')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.fin_customers')),
                ('repeat_every', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.fin_companyrepeatevery')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.fin_vendors')),
            ],
        ),
        migrations.RenameModel(
            old_name='Recurring_Bill_Items',
            new_name='Fin_Recurring_Bill_Items',
        ),
        migrations.RenameModel(
            old_name='Recurring_Bill_Reference',
            new_name='Fin_Recurring_Bill_Reference',
        ),
        migrations.AlterField(
            model_name='employee_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 8)),
        ),
        migrations.AlterField(
            model_name='holiday_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 8)),
        ),
        migrations.RenameModel(
            old_name='Recurring_Bill_History',
            new_name='Fin_Recurring_Bill_History',
        ),
        migrations.DeleteModel(
            name='Recurring_Bills',
        ),
        migrations.AlterField(
            model_name='fin_recurring_bill_history',
            name='recurring_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.fin_recurring_bills'),
        ),
    ]
