# Generated by Django 4.2.6 on 2024-03-23 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_tax_rate_fin_recurring_bill_items_tax_rate_gst_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fin_recurring_bill_items',
            old_name='tax_rate_gst',
            new_name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='fin_recurring_bill_items',
            name='tax_rate_igst',
        ),
    ]
