# Generated by Django 4.2.6 on 2024-03-02 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_fin_recurring_bill_items_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_recurring_bills',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='recurring_bill_attachments'),
        ),
        migrations.AlterField(
            model_name='employee_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 2)),
        ),
        migrations.AlterField(
            model_name='holiday_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 2)),
        ),
    ]
