# Generated by Django 4.2.6 on 2024-03-04 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_fin_recurring_bills_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 4)),
        ),
        migrations.AlterField(
            model_name='fin_recurring_bills',
            name='grand_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fin_recurring_bills',
            name='sub_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holiday_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 4)),
        ),
    ]
