# Generated by Django 4.2.6 on 2024-03-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_employee_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fin_recurring_bills',
            name='adjustment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fin_recurring_bills',
            name='advanceAmount_paid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fin_recurring_bills',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fin_recurring_bills',
            name='cgst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fin_recurring_bills',
            name='sgst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fin_recurring_bills',
            name='shipping_charge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fin_recurring_bills',
            name='taxAmount_igst',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
